### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by StableInquest** [enlyth/sd-webui-riffusion#1]
```
Error running install.py for extension /stable-diffusion-webui/extensions/sd-webui-riffusion.
Command: "/stable-diffusion-webui/venv/bin/python3.10" "/stable-diffusion-webui/extensions/sd-webui-riffusion/install.py"
Error code: 1
stdout: 
Initializing Riffusion

[Riffusion] Installing torchaudio...

stderr: Traceback (most recent call last):
  File "/stable-diffusion-webui/extensions/sd-webui-riffusion/install.py", line 15, in <module>
    run(
  File "/stable-diffusion-webui/launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: [Riffusion] Couldn't torchaudio..
Command: "/stable-diffusion-webui/venv/bin/python3.10" -m pip install torchaudio==0.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113"
Error code: 2
stdout: <empty>
stderr: /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

**Comment by enlyth** [comment]
My bad, the extra quote in the command was causing this, fixed on master

**Comment by StableInquest** [comment]
Thanks!
