### ISSUE TITLE
Local variable 'audio' referenced before assignment

### ISSUE THREAD

**Issue by kenster4000** [enlyth/sd-webui-riffusion#10]
Steps to reproduce:

- Load up riffusion-model-v1.ckpt (or actually any model)
- Enable script
- Generate
- Hit "Refresh Inline Audio" button
- MP3 player appears, play, audio works!
- Hit Generate again - error.

Traceback (most recent call last):
  File "e:\__workspace\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "e:\__workspace\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 980, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "e:\__workspace\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 891, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "e:\__workspace\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1845, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "e:\__workspace\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 204, in audio_from_file
    data = np.array(audio.get_array_of_samples())
UnboundLocalError: local variable 'audio' referenced before assignment

**Comment by pyr0ball** [comment]
Confirmed the same behavior from my instance

**Comment by plusmaa** [comment]
Same for me.
