### ISSUE TITLE
BUG: InverseMelScale unexpected argument

### ISSUE THREAD

**Issue by ibaraki-douji** [enlyth/sd-webui-riffusion#34]
So i installed the riffusion on the A1111 webui and i got this error :

```
Traceback (most recent call last):
      File "/workspace/audio-generation-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/workspace/audio-generation-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/workspace/audio-generation-webui/modules/txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "/workspace/audio-generation-webui/modules/scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "/workspace/audio-generation-webui/extensions/sd-webui-riffusion/scripts/riffusion.py", line 135, in run
        wav_bytes, duration_s = self.wav_bytes_from_spectrogram_image(
      File "/workspace/audio-generation-webui/extensions/sd-webui-riffusion/scripts/riffusion.py", line 186, in wav_bytes_from_spectrogram_image
        samples = self.waveform_from_spectrogram(
      File "/workspace/audio-generation-webui/extensions/sd-webui-riffusion/scripts/riffusion.py", line 296, in waveform_from_spectrogram
        mel_inv_scaler = torchaudio.transforms.InverseMelScale(
    TypeError: InverseMelScale.__init__() got an unexpected keyword argument 'max_iter'
```

I managed to "fix" it (idk if it's the fix but it works).

On line 304 of the `riffusion.py` file remove the `max_iter=max_mel_iters` which is not in the `InverseMelScale` constructor/function.
![image](https://github.com/enlyth/sd-webui-riffusion/assets/72337875/e8523386-c2da-4645-b5df-b51dd495e36e)

I keep it open until this is resolved in the github code.

**Comment by xiaolubuhuizhuzhou** [comment]
Have the same problem.

**Comment by ibaraki-douji** [comment]
@xiaolubuhuizhuzhou just remove the lines with max_iter=max_mel_iters and it fixes it.

**Comment by xiaolubuhuizhuzhou** [comment]
> @xiaolubuhuizhuzhou just remove the lines with max_iter=max_mel_iters and it fixes it.

Thanks! It works. I found this parameter have been removed since torchaudio 2.1.0.

**Comment by Ede2023** [comment]
It works for me, thank you!
