### ISSUE TITLE
Torch is not able to use GPU

### ISSUE THREAD

**Issue by xyiphk** [enlyth/sd-webui-riffusion#38]
After I add this sd-webui-riffusion to SD webui, it said "Torch is not able to use GPU" and I cannot start the SD webui or I don't use GPU.
The big issue is that although I remove the sd-webui-riffusion from my SD webui, it cannot get back that it also said "Torch is not able to use GPU" or I don't use GPU.
CPU: AMD Ryzen 7 5800H with Radeon Graphics
GPU: RTX 3060 Laptop + AMD Radeon Graphics

**Comment by telos954** [comment]
Just posting that I'm having the same issue, and even after removing all the files I can find associated with it, I can not launch the webui. 

CPU: AMD Ryzen 5 3600x
GPU: EVGA GeForce RTX 3070 Ti FTW3 Ultra

**Comment by jacob-willden** [comment]
I am also facing the same issue after adding `sd-webui-riffusion` to the Stable Diffusion Web UI.
```
venv "C:\Users\true3dnow\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.4
Commit hash: feee37d75f1b168768014e4634dcb156ee649c05
Traceback (most recent call last):
  File "C:\Users\true3dnow\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "C:\Users\true3dnow\stable-diffusion-webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\true3dnow\stable-diffusion-webui\modules\launch_utils.py", line 386, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .
```
Steps to reproduce:
1. Install and run [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) (via the [Automatic Installation on Windows](https://github.com/AUTOMATIC1111/stable-diffusion-webui#automatic-installation-on-windows) section).
2. Check that you can generate images with any model.
3. Install `sd-webui-riffusion` as instructed, including installing `ffmpeg` and cloning the repo into the `extensions` folder.
4. Close and re-run the Stable Diffusion Web UI via `webui-user.bat`.
5. Notice that the "Torch is not able to use GPU" error now appears and trying to generate any images (once the Web UI loads) fails. It's worth noting that removing the extension does not fix the issues.
6. Delete the Web UI and reinstall it without the extension.
7. Run the Web UI once more and notice that generating images works again.

It's worth noting that I've tried restarting my computer after installing `sd-webui-riffusion` and running it with Stable Diffusion, and then tried running it again, with the same result.

My computer's stats:
- Operating System: Windows 10
- CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, 3600 Mhz, 8 Cores, 16 Logical Processors
- GPU: NVIDIA GeForce RTX 2080 Ti

I'm happy to share any other information needed to troubleshoot this.

**Comment by 4aiman** [comment]
Same here. Windows 11, Ryzen 3600, RTX4070.
Riffusion plugin breaks torch's ability to utilize CUDA

**Comment by jacob-willden** [comment]
Just to let everyone know, I found another repository that allows for self-hosting Riffusion, [tts-generation-webui](https://github.com/rsxdalv/tts-generation-webui). I'm able to install it alongside [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and use both (not necessary if you only want to generate audio though).
