### ISSUE TITLE
No module named 'pedalboard_native'

### ISSUE THREAD

**Issue by afrofail** [enlyth/sd-webui-riffusion#9]
I manually installed pedalboard because it wasn't automatically installing, placed in the venv directory. Now I'm recieving this error when I start Automatic1111 repo.

**Comment by afrofail** [comment]
Launching Web UI with arguments: --disable-safe-unpickle --deepdanbooru --xformers --no-half-vae
Error loading script: riffusion.py
Traceback (most recent call last):
  File "M:\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "M:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "M:\stable-diffusion-webui\extensions\sd-webui-riffusion\scripts\riffusion.py", line 18, in <module>
    from pedalboard.io import AudioFile
ModuleNotFoundError: No module named 'pedalboard'

**Comment by wedgeewoo** [comment]
pip install pedalboard

**Comment by jvoxel** [comment]
I have this error trying to start last ben's A1111 Colab 
Error loading script: riffusion.py
Traceback (most recent call last):
```
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-riffusion/scripts/riffusion.py", line 18, in <module>
    from pedalboard.io import AudioFile
ModuleNotFoundError: No module named 'pedalboard'
```
